# Default values for app1.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
appname: frontend
replicaCount: 1

image:
  repository: busybox
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "3.5"


